sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 9669
  alioss:
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: zanno
    endpoint: oss-cn-hangzhou.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    password: 9669
    database: 0
  wechat:
    appid: wx5b8c580848a491b4
    secret: fa23a11a5a32ce77932dea905e48b6b2